"""Edit table columns

Revision ID: e098f5484487
Revises: 78ecb0186b17
Create Date: 2023-07-27 17:19:43.798022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e098f5484487'
down_revision = '78ecb0186b17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('nakladnoy', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'nakladnoy')
    # ### end Alembic commands ###
